version: '3.1'

services:
  postgres:
    container_name: pg_book
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: